import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Compound from "@compound-finance/compound-js";
import CalculateAPY from "../apy.js";

export default function Home({ APYS }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Compound Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2 className={styles.title}>Compound Dashboard</h2>

        <h4 className={styles.description}>
          Listing the Supply APY and COMP APY Reward
        </h4>

        <table className="table">
          <thead>
            <tr>
              <th>Coin Image</th>
              <th>Underlying</th>
              <th>Underlying</th>
              <th>Comp APY</th>
              <th>Total APY</th>
            </tr>
          </thead>
          <tbody>
            {APYS &&
              APYS.map((item, index) => (
                <tr key={index}>
                  <td>
                    <img
                      src={`img/${item.ticker}.png`}
                      alt={item.ticker}
                      width="25px"
                      height="25px"
                    />
                  </td>
                  <td>{item.ticker}</td>
                  <td>{Number(item.supplyApy).toFixed(2)}%</td>
                  <td>{Number(item.compApy).toFixed(2)}%</td>
                  <td>{Number(item.supplyApy + item.compApy).toFixed(2)}%</td>
                </tr>
              ))}
          </tbody>
        </table>
      </main>
    </div>
  );
}

export async function getServerSideProps(context) {
  const APYS = await Promise.all([
    CalculateAPY(Compound.cDAI, "DAI"),
    CalculateAPY(Compound.cUSDC, "USDC"),
    CalculateAPY(Compound.cUSDT, "USDT"),
  ]);

  console.log("APYS:", APYS);

  return {
    props: {
      APYS,
    },
  };
}
